#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# new-api Management Script
# Commands: deploy | migrate | update | remove
# ============================================================

INSTALL_DIR="$(cd "$(dirname "$0")" && pwd)"
DATA_DIR="$INSTALL_DIR/data"
LOGS_DIR="$INSTALL_DIR/logs"
ENV_FILE="$INSTALL_DIR/.env"
COMPOSE_FILE="$INSTALL_DIR/docker-compose.yml"
IMAGE_TAR="$INSTALL_DIR/new-api-image.tar"
VERSION_FILE="$INSTALL_DIR/VERSION"
LOCK_FILE="/tmp/new-api-manage.lock"
COMPOSE_PROJECT="new-api"

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }
die()   { error "$@"; exit 1; }

banner() {
  echo -e "${CYAN}${BOLD}"
  echo "  _   _      _     ___  ____"
  echo " | \\ | | ___| |__ / _ \\/ ___|"
  echo " |  \\| |/ _ \\ '_ \\ | | \\___ \\"
  echo " | |\\  |  __/ |_) | |_| |__) |"
  echo " |_| \\_|\\___|_.__/ \\___/____/"
  echo -e "${NC}"
}

# --- Lock ---
acquire_lock() {
  exec 200>"$LOCK_FILE"
  flock -n 200 || die "Another manage.sh instance is running. If stale, rm $LOCK_FILE"
}
release_lock() {
  rm -f "$LOCK_FILE"
}

# --- Docker helpers ---
check_docker() {
  if ! command -v docker &>/dev/null; then
    warn "Docker not found. Installing..."
    install_docker
  fi
  if ! docker info &>/dev/null; then
    warn "Docker daemon not running. Starting..."
    sudo systemctl start docker || die "Failed to start Docker. Run: sudo systemctl start docker"
  fi
  info "Docker is running."
}

install_docker() {
  if [ ! -f /etc/os-release ]; then
    die "Cannot detect OS. Install Docker manually: https://docs.docker.com/engine/install/"
  fi
  source /etc/os-release
  case "$ID" in
    ubuntu|debian)
      info "Installing Docker via official script..."
      curl -fsSL https://get.docker.com | sudo sh
      sudo usermod -aG docker "$USER"
      sudo systemctl enable --now docker
      warn "You may need to log out and back in for docker group to take effect."
      warn "If 'docker' still fails, run: newgrp docker"
      ;;
    centos|rhel|rocky|almalinux)
      info "Installing Docker via official script..."
      curl -fsSL https://get.docker.com | sudo sh
      sudo systemctl enable --now docker
      sudo usermod -aG docker "$USER"
      ;;
    *)
      die "Unsupported OS: $ID. Install Docker manually: https://docs.docker.com/engine/install/"
      ;;
  esac
}

check_docker_compose() {
  if ! docker compose version &>/dev/null; then
    die "docker compose plugin not found. Install it: https://docs.docker.com/compose/install/"
  fi
}

load_image() {
  local tar="$1"
  if [ ! -f "$tar" ]; then
    die "Image tar not found: $tar"
  fi
  info "Loading Docker image from $tar..."
  local output
  output="$(docker load -i "$tar" 2>&1)" || die "Failed to load image: $output"
  echo "$output"
  local loaded_tag
  loaded_tag="$(echo "$output" | grep -oP 'Loaded image: \K.*' | head -1)"
  if [ -n "$loaded_tag" ]; then
    info "Loaded image: $loaded_tag"
  fi
}

get_version() {
  if [ -f "$VERSION_FILE" ]; then
    cat "$VERSION_FILE" | tr -d '[:space:]' | sed 's/^v//'
  else
    echo "unknown"
  fi
}

# --- Generate .env ---
generate_env() {
  if [ -f "$ENV_FILE" ]; then
    info ".env already exists, keeping existing configuration."
    source "$ENV_FILE"
    return
  fi

  info "Generating .env with default passwords..."
  cat > "$ENV_FILE" <<EOF
# new-api environment configuration
# Generated by manage.sh on $(date)

POSTGRES_USER=root
POSTGRES_PASSWORD=123456
POSTGRES_DB=new-api
REDIS_PASSWORD=123456
SESSION_SECRET=newapi-session-secret-default
NEW_API_PORT=3000
NEW_API_VERSION=$(get_version)
EOF

  echo ""
  echo -e "${RED}${BOLD}╔══════════════════════════════════════════════════════════════╗${NC}"
  echo -e "${RED}${BOLD}║  WARNING: Default passwords are in use!                     ║${NC}"
  echo -e "${RED}${BOLD}║  Edit $ENV_FILE  ║${NC}"
  echo -e "${RED}${BOLD}║  to change POSTGRES_PASSWORD, REDIS_PASSWORD,               ║${NC}"
  echo -e "${RED}${BOLD}║  and SESSION_SECRET before production use!                   ║${NC}"
  echo -e "${RED}${BOLD}╚══════════════════════════════════════════════════════════════╝${NC}"
  echo ""

  source "$ENV_FILE"
}

# --- Generate docker-compose.yml ---
generate_compose() {
  info "Generating docker-compose.yml..."
  cat > "$COMPOSE_FILE" <<'COMPOSE_EOF'
services:
  new-api:
    image: new-api:${NEW_API_VERSION}
    container_name: new-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "${NEW_API_PORT:-3000}:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - SQL_DSN=postgresql://${POSTGRES_USER:-root}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-new-api}
      - REDIS_CONN_STRING=redis://:${REDIS_PASSWORD}@redis:6379
      - SESSION_SECRET=${SESSION_SECRET}
      - TZ=Asia/Shanghai
      - ERROR_LOG_ENABLED=true
      - BATCH_UPDATE_ENABLED=true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - new-api-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: new-api-redis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    networks:
      - new-api-network

  postgres:
    image: postgres:15-alpine
    container_name: new-api-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-new-api}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - new-api-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-root} -d ${POSTGRES_DB:-new-api}"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pg_data:
  redis_data:

networks:
  new-api-network:
    driver: bridge
COMPOSE_EOF
}

# --- Wait for health ---
wait_for_healthy() {
  local port="${1:-3000}"
  local max_wait=120
  local elapsed=0
  info "Waiting for new-api to be healthy (max ${max_wait}s)..."
  while [ $elapsed -lt $max_wait ]; do
    if curl -sf "http://localhost:$port/api/status" 2>/dev/null | grep -q '"success"'; then
      info "new-api is healthy!"
      return 0
    fi
    sleep 5
    elapsed=$((elapsed + 5))
    printf "  ...%ds\r" "$elapsed"
  done
  warn "new-api did not become healthy within ${max_wait}s. Check logs:"
  warn "  docker compose -f $COMPOSE_FILE logs new-api"
  return 1
}

# --- Compose wrapper ---
dc() {
  docker compose -p "$COMPOSE_PROJECT" -f "$COMPOSE_FILE" --env-file "$ENV_FILE" "$@"
}

# ============================================================
# COMMAND: deploy
# ============================================================
cmd_deploy() {
  banner
  acquire_lock
  trap release_lock EXIT

  check_docker
  check_docker_compose

  # Load image and detect version
  local LOADED_OUTPUT
  LOADED_OUTPUT="$(load_image "$IMAGE_TAR")"
  local LOADED_TAG
  LOADED_TAG="$(echo "$LOADED_OUTPUT" | grep -oP 'Loaded image: \K.*' | head -1)"
  if [ -n "$LOADED_TAG" ]; then
    # Extract version from tag (e.g., "new-api:1.1.0" -> "1.1.0")
    local DETECTED_VERSION="${LOADED_TAG##*:}"
    if [ "$DETECTED_VERSION" != "unknown" ] && [ "$DETECTED_VERSION" != "latest" ]; then
      echo "$DETECTED_VERSION" > "$VERSION_FILE"
      info "Detected image version: $DETECTED_VERSION"
    fi
  fi

  # Generate config
  generate_env
  # Ensure NEW_API_VERSION matches the loaded image
  if [ -n "${LOADED_TAG:-}" ]; then
    local DETECTED_V="${LOADED_TAG##*:}"
    if [ "$DETECTED_V" != "unknown" ] && [ "$DETECTED_V" != "latest" ]; then
      if grep -q '^NEW_API_VERSION=' "$ENV_FILE" 2>/dev/null; then
        sed -i "s/^NEW_API_VERSION=.*/NEW_API_VERSION=$DETECTED_V/" "$ENV_FILE"
      fi
    fi
  fi
  generate_compose

  # Create directories
  mkdir -p "$DATA_DIR" "$LOGS_DIR"

  # Check for migration data
  local MIGRATION_SQL="$INSTALL_DIR/data/pg_dump.sql"
  if [ -f "$MIGRATION_SQL" ]; then
    echo ""
    info "Detected migration data (pg_dump.sql). Entering migration-restore mode..."
    source "$ENV_FILE"

    # Start only postgres first
    info "Starting PostgreSQL for database restore..."
    dc up -d postgres
    local pg_wait=0
    while [ $pg_wait -lt 60 ]; do
      if dc exec -T postgres pg_isready -U "${POSTGRES_USER:-root}" -d "${POSTGRES_DB:-new-api}" &>/dev/null; then
        break
      fi
      sleep 3
      pg_wait=$((pg_wait + 3))
    done
    if [ $pg_wait -ge 60 ]; then
      die "PostgreSQL did not become ready in 60s"
    fi
    info "PostgreSQL is ready."

    # Restore database
    info "Restoring database from pg_dump.sql..."
    cat "$MIGRATION_SQL" | dc exec -T postgres psql -U "${POSTGRES_USER:-root}" -d "${POSTGRES_DB:-new-api}" >/dev/null
    info "Database restored."

    # Copy app data and logs
    if [ -d "$INSTALL_DIR/data/app-data" ]; then
      info "Restoring application data..."
      cp -a "$INSTALL_DIR/data/app-data/." "$DATA_DIR/"
    fi
    if [ -d "$INSTALL_DIR/data/logs" ]; then
      info "Restoring logs..."
      cp -a "$INSTALL_DIR/data/logs/." "$LOGS_DIR/"
    fi
  fi

  # Start all services
  info "Starting all services..."
  dc up -d --remove-orphans

  # Wait for health
  source "$ENV_FILE"
  wait_for_healthy "${NEW_API_PORT:-3000}" || true

  # Print info
  echo ""
  echo -e "${GREEN}${BOLD}========================================${NC}"
  echo -e "${GREEN}${BOLD}  new-api deployed successfully!${NC}"
  echo -e "${GREEN}${BOLD}========================================${NC}"
  echo ""
  echo "  URL:      http://$(hostname -I 2>/dev/null | awk '{print $1}' || echo 'localhost'):${NEW_API_PORT:-3000}"
  echo "  Version:  $(get_version)"
  echo "  Data:     $DATA_DIR"
  echo "  Logs:     $LOGS_DIR"
  echo "  Config:   $ENV_FILE"
  echo ""
  echo "  Default admin: root / 123456"
  echo "  Manage:   ./manage.sh [migrate|update|remove]"
  echo ""
}

# ============================================================
# COMMAND: migrate
# ============================================================
cmd_migrate() {
  banner
  acquire_lock
  trap release_lock EXIT

  if [ ! -f "$COMPOSE_FILE" ] || [ ! -f "$ENV_FILE" ]; then
    die "No deployment found. Run './manage.sh deploy' first."
  fi

  source "$ENV_FILE"
  local VERSION="$(get_version)"
  local STAGING_DIR="$(mktemp -d)"

  info "Preparing migration package for v$VERSION..."

  # Stop new-api (keep postgres running for dump)
  info "Stopping new-api container..."
  dc stop new-api 2>/dev/null || true

  # Dump PostgreSQL
  info "Dumping PostgreSQL database..."
  mkdir -p "$STAGING_DIR/data"
  dc exec -T postgres pg_dump -U "${POSTGRES_USER:-root}" -d "${POSTGRES_DB:-new-api}" --clean --if-exists > "$STAGING_DIR/data/pg_dump.sql"
  if [ ! -s "$STAGING_DIR/data/pg_dump.sql" ]; then
    die "pg_dump produced empty output. Check if postgres is running."
  fi
  info "Database dump: $(du -h "$STAGING_DIR/data/pg_dump.sql" | cut -f1)"

  # Copy app data and logs
  if [ -d "$DATA_DIR" ] && [ "$(ls -A "$DATA_DIR" 2>/dev/null)" ]; then
    info "Copying application data..."
    mkdir -p "$STAGING_DIR/data/app-data"
    cp -a "$DATA_DIR/." "$STAGING_DIR/data/app-data/"
  fi
  if [ -d "$LOGS_DIR" ] && [ "$(ls -A "$LOGS_DIR" 2>/dev/null)" ]; then
    info "Copying logs..."
    mkdir -p "$STAGING_DIR/data/logs"
    cp -a "$LOGS_DIR/." "$STAGING_DIR/data/logs/"
  fi

  # Copy .env
  if [ -f "$ENV_FILE" ]; then
    cp "$ENV_FILE" "$STAGING_DIR/.env"
    info "Copied .env (contains passwords - keep this archive secure!)"
  fi

  # Always re-save the current image to ensure version consistency
  info "Saving current Docker image (new-api:$VERSION)..."
  docker save "new-api:$VERSION" -o "$STAGING_DIR/new-api-image.tar"

  # Copy manage.sh and VERSION
  cp "$INSTALL_DIR/manage.sh" "$STAGING_DIR/manage.sh"
  chmod +x "$STAGING_DIR/manage.sh"
  cp "$VERSION_FILE" "$STAGING_DIR/VERSION"

  # Stop all services
  info "Stopping all services..."
  dc stop 2>/dev/null || true

  # Create archive
  local ARCHIVE_NAME="new-api-$VERSION-migration.tar.gz"
  tar czf "$INSTALL_DIR/$ARCHIVE_NAME" -C "$STAGING_DIR" .

  # Cleanup
  rm -rf "$STAGING_DIR"

  # Restart services
  info "Restarting services..."
  dc start 2>/dev/null || true

  local FILE_SIZE="$(du -h "$INSTALL_DIR/$ARCHIVE_NAME" | cut -f1)"
  echo ""
  echo -e "${GREEN}${BOLD}========================================${NC}"
  echo -e "${GREEN}${BOLD}  Migration package created!${NC}"
  echo -e "${GREEN}${BOLD}========================================${NC}"
  echo ""
  echo "  Archive:  $INSTALL_DIR/$ARCHIVE_NAME"
  echo "  Size:     $FILE_SIZE"
  echo ""
  echo "  To deploy on a new machine:"
  echo "    scp $ARCHIVE_NAME user@newserver:~/"
  echo "    mkdir -p ~/new-api && tar xzf $ARCHIVE_NAME -C ~/new-api"
  echo "    cd ~/new-api && ./manage.sh deploy"
  echo ""
  echo -e "  ${YELLOW}WARNING: This archive contains the full database and passwords.${NC}"
  echo -e "  ${YELLOW}Keep it secure during transfer and delete after use.${NC}"
  echo ""
}

# ============================================================
# COMMAND: update
# ============================================================
cmd_update() {
  banner
  acquire_lock
  trap release_lock EXIT

  if [ ! -f "$COMPOSE_FILE" ] || [ ! -f "$ENV_FILE" ]; then
    die "No deployment found. Run './manage.sh deploy' first."
  fi

  local ARCHIVE_PATH="${1:-}"
  if [ -z "$ARCHIVE_PATH" ]; then
    # Look for archives in install dir
    local found
    found="$(ls -t "$INSTALL_DIR"/new-api-*.tar.gz 2>/dev/null | grep -v migration | head -1)"
    if [ -n "$found" ]; then
      ARCHIVE_PATH="$found"
      info "Found archive: $ARCHIVE_PATH"
    else
      die "Usage: ./manage.sh update /path/to/new-api-X.Y.Z.tar.gz"
    fi
  fi

  if [ ! -f "$ARCHIVE_PATH" ]; then
    die "Archive not found: $ARCHIVE_PATH"
  fi

  source "$ENV_FILE"
  local OLD_VERSION="$NEW_API_VERSION"

  # Extract to temp dir
  local TMP_DIR="$(mktemp -d)"
  trap 'rm -rf "$TMP_DIR" 2>/dev/null; release_lock' EXIT

  info "Extracting update package..."
  tar xzf "$ARCHIVE_PATH" -C "$TMP_DIR"

  # Read new version
  local NEW_VERSION
  NEW_VERSION="$(cat "$TMP_DIR/VERSION" 2>/dev/null | tr -d '[:space:]' | sed 's/^v//')"
  if [ -z "$NEW_VERSION" ]; then
    die "Cannot determine new version from archive."
  fi

  info "Updating: $OLD_VERSION -> $NEW_VERSION"

  if [ "$OLD_VERSION" = "$NEW_VERSION" ]; then
    warn "Same version ($NEW_VERSION). Updating anyway (force-recreate)."
  fi

  # Load new image
  load_image "$TMP_DIR/new-api-image.tar"

  # Update .env
  sed -i "s/^NEW_API_VERSION=.*/NEW_API_VERSION=$NEW_VERSION/" "$ENV_FILE"
  info "Updated NEW_API_VERSION in .env"

  # Update VERSION file
  echo "$NEW_VERSION" > "$VERSION_FILE"

  # Copy new manage.sh
  cp "$TMP_DIR/manage.sh" "$INSTALL_DIR/manage.sh"
  chmod +x "$INSTALL_DIR/manage.sh"

  # Regenerate compose with new version
  generate_compose

  # Recreate only the new-api container (NOT postgres or redis)
  info "Recreating new-api container with new image..."
  dc up -d --force-recreate new-api --no-deps

  # Wait for health
  wait_for_healthy "${NEW_API_PORT:-3000}" || true

  # Clean up old image
  if [ -n "$OLD_VERSION" ] && [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
    info "Removing old image new-api:$OLD_VERSION..."
    docker rmi "new-api:$OLD_VERSION" 2>/dev/null || true
  fi
  docker image prune -f 2>/dev/null || true

  # Cleanup temp
  rm -rf "$TMP_DIR"

  echo ""
  echo -e "${GREEN}${BOLD}========================================${NC}"
  echo -e "${GREEN}${BOLD}  Update complete!${NC}"
  echo -e "${GREEN}${BOLD}========================================${NC}"
  echo ""
  echo "  Version:  $OLD_VERSION -> $NEW_VERSION"
  echo "  URL:      http://$(hostname -I 2>/dev/null | awk '{print $1}' || echo 'localhost'):${NEW_API_PORT:-3000}"
  echo ""
  echo "  Rollback: edit NEW_API_VERSION in $ENV_FILE and run:"
  echo "    ./manage.sh update  (or dc up -d --force-recreate new-api --no-deps)"
  echo ""
}

# ============================================================
# COMMAND: remove
# ============================================================
cmd_remove() {
  banner
  acquire_lock
  trap release_lock EXIT

  echo -e "${RED}${BOLD}╔══════════════════════════════════════════════════════════════╗${NC}"
  echo -e "${RED}${BOLD}║  WARNING: This will remove ALL new-api data and containers! ║${NC}"
  echo -e "${RED}${BOLD}║  This action is IRREVERSIBLE.                               ║${NC}"
  echo -e "${RED}${BOLD}╚══════════════════════════════════════════════════════════════╝${NC}"
  echo ""
  read -rp "Type 'yes' to confirm complete removal: " CONFIRM
  if [ "$CONFIRM" != "yes" ]; then
    info "Aborted."
    return 0
  fi

  # Stop and remove containers
  if [ -f "$COMPOSE_FILE" ]; then
    info "Stopping and removing containers..."
    dc down -v --remove-orphans 2>/dev/null || true
  else
    # Try to remove by container name even without compose file
    info "Removing containers by name..."
    docker rm -f new-api new-api-redis new-api-postgres 2>/dev/null || true
  fi

  # Remove Docker named volumes
  info "Removing Docker volumes..."
  docker volume rm new-api_pg_data new-api_redis_data 2>/dev/null || true

  # Remove all new-api related images
  info "Removing new-api Docker images..."
  local images
  images="$(docker images --format '{{.Repository}}:{{.Tag}}' | grep -i 'new-api' || true)"
  if [ -n "$images" ]; then
    echo "$images" | while read -r img; do
      info "  Removing image: $img"
      docker rmi "$img" 2>/dev/null || true
    done
  fi
  # Also remove dangling images
  docker image prune -f 2>/dev/null || true

  # Remove Docker network
  info "Removing Docker network..."
  docker network rm new-api_new-api-network new-api-network 2>/dev/null || true

  # Remove user data directories
  info "Removing data directories..."
  if [ -d "$DATA_DIR" ]; then
    rm -rf "$DATA_DIR"
    info "  Removed: $DATA_DIR"
  fi
  if [ -d "$LOGS_DIR" ]; then
    rm -rf "$LOGS_DIR"
    info "  Removed: $LOGS_DIR"
  fi

  # Remove config files
  info "Removing configuration files..."
  rm -f "$ENV_FILE" "$COMPOSE_FILE"
  info "  Removed: .env, docker-compose.yml"

  # Remove lock file
  rm -f "$LOCK_FILE"

  echo ""
  echo -e "${GREEN}${BOLD}========================================${NC}"
  echo -e "${GREEN}${BOLD}  new-api completely removed!${NC}"
  echo -e "${GREEN}${BOLD}========================================${NC}"
  echo ""
  echo "  All containers, volumes, images, data, and config have been deleted."
  echo "  The install directory still exists: $INSTALL_DIR"
  echo "  To redeploy: ./manage.sh deploy"
  echo ""
}

# ============================================================
# Main
# ============================================================
case "${1:-}" in
  deploy)  cmd_deploy ;;
  migrate) cmd_migrate ;;
  update)  shift; cmd_update "$@" ;;
  remove)  cmd_remove ;;
  *)
    banner
    echo "Usage: ./manage.sh <command> [options]"
    echo ""
    echo "Commands:"
    echo "  deploy         First-time deployment (auto-install Docker, start services)"
    echo "  migrate        Package all data for migration to another machine"
    echo "  update [path]  Update to new version (preserves database)"
    echo "  remove         Remove all containers, images, data, and config"
    echo ""
    echo "Options:"
    echo "  update <path>  Path to new version tar.gz archive"
    echo ""
    ;;
esac
